### ISSUE TITLE
putting node_modules into a git repo

### ISSUE THREAD

**Issue by Kelvinm** [alexhsamuel/locator#17]
I'm having a LOT of git trouble with whatever the last round of changes was made, is this the equivalent of putting a virtualenv in git?

**Comment by alexhsamuel** [comment]
node_modules shouldn't go with git.  This is essentially the local cache of js modules constructed by npm, from `package.json` and `package-lock.json`.  Add it to .gitignore, and run `npm install` to rebuild it when needed.

**Comment by alexhsamuel** [comment]
All I did was rename `react` to `react-boilerplate`, so that we can use `react` for our new, from-scratch project.  Blow away your old `react/node_modules`.  You can rebuild it in the old boilerplate directory with `npm install`.

**Comment by Kelvinm** [comment]
ah, you got to it already.  i was struggling through after the last round of changes to clean up my git environment and got pretty confused.  I just sorted it just now, came back to close this.
